const jobFields = [
    { title: 'Software Engineer', experience: '2+ years' },
    { title: 'Data Scientist', experience: '3+ years' },
    { title: 'Product Manager', experience: '5+ years' },
    { title: 'Graphic Designer', experience: '1+ years' },
    { title: 'Sales Associate', experience: 'Entry-level' },
    { title: 'Human Resources Specialist', experience: '2+ years' },
    { title: 'Marketing Coordinator', experience: '3+ years' },
    { title: 'Civil Engineer', experience: '4+ years' },
    { title: 'Financial Analyst', experience: '2+ years' },
    { title: 'Nurse Practitioner', experience: '5+ years' },
    { title: 'Pharmaceutical Sales', experience: 'Entry-level' },
    { title: 'Web Developer', experience: '2+ years' },
    { title: 'Mechanical Engineer', experience: '3+ years' },
    { title: 'Interior Designer', experience: '1+ years' },
    { title: 'Public Relations Specialist', experience: '4+ years' },
    { title: 'Accountant', experience: 'CPA preferred' },
    { title: 'Cloud Solutions Architect', experience: 'Azure/GCP/AWS certification' },
    { title: 'AI Research Scientist', experience: 'PhD preferred' },
    { title: 'Real Estate Agent', experience: 'License required' },
    { title: 'Logistics Coordinator', experience: '2+ years' },
    { title: 'UX/UI Designer', experience: '2+ years' },
    { title: 'Network Administrator', experience: 'Cisco certification preferred' },
    { title: 'Cybersecurity Specialist', experience: 'Certification required' },
    { title: 'Project Manager', experience: 'PMP certification' },
    { title: 'Social Media Manager', experience: '2+ years' },
    { title: 'Technical Writer', experience: '3+ years' },
    { title: 'Environmental Engineer', experience: '2+ years' },
    { title: 'Legal Assistant', experience: 'Paralegal certificate' },
    { title: 'Dental Hygienist', experience: 'License required' },
    { title: 'Biomedical Engineer', experience: '2+ years' }
];

export default jobFields;
